### ISSUE TITLE
Merge SendData

### ISSUE THREAD

**Issue by tylerjwatson** [nicatronTg/early-api#1]
`NetMessage.SendData` contents must be merged into the new solution to bring sending new packet information into the server.  Don't worry if it doesn't compile for now.

### Make new issues under this milestone to fix further components that break from this change!

**Comment by Enerdy** [comment]
10ff7996cb995e6a51f02e82551d73280e3bb1dc

**Comment by Enerdy** [comment]
bd45769692fc53d7736ea8e88a81036a18fa2c61
